sudo: required

language: generic

services:
  - docker

before_install:
  # - source version.sh
  # - echo $VERSION
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -f latest/Dockerfile -t mc303/hass-node-red-arm64v8 .

script:
  - docker run -d mc303/hass-node-red-arm64v8:latest
  - docker ps | grep lates
  # - docker run -d nodered/node-red-docker:rpi-v10
  # - docker ps | grep rpi-v10

after_success:
  - if [ -n "$TRAVIS_TAG" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push nodered/node-red-docker;
fi
